# Generated by Django 4.2.4 on 2023-09-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='senha_adicional',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
