# Generated by Django 4.2.4 on 2023-09-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='promocao',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
