# Generated by Django 4.2.5 on 2023-10-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocao', '0003_promocao_mercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='image',
            field=models.ImageField(default='image1.jpg', upload_to='promocoes_images/'),
            preserve_default=False,
        ),
    ]
