# Generated by Django 4.2.5 on 2023-09-29 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
        ('stories', '0002_stories_delete_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='mercado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mercado.mercado'),
            preserve_default=False,
        ),
    ]
