# Generated by Django 4.2.4 on 2023-10-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_stories_mercado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='video',
            new_name='foto',
        ),
    ]
