# Generated by Django 4.2.4 on 2023-10-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_telefone_whatsapp_cliente_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefone',
            old_name='numero',
            new_name='Telefone',
        ),
        migrations.RenameField(
            model_name='whatsapp',
            old_name='numero',
            new_name='telefone',
        ),
    ]
