# Generated by Django 4.2.4 on 2023-10-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_rename_numero_telefone_telefone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefone',
            old_name='Telefone',
            new_name='numero',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.telefone', verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.whatsapp', verbose_name='WhatsApp'),
        ),
    ]
