# Generated by Django 4.2.4 on 2023-10-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_rename_telefone_telefone_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WhatsApp',
        ),
    ]
